public class CICDDeploymentClass {

    public static String firstDeploy = 'Im the first deploy for base';
    public static String secondDeploy = 'Im the second deploy for base';
    public static String thirdDeploy = 'Im the third deploy for base';
    public static String thirdDeploy = 'Im the fourth deploy for base';
    public static String thirdDeploy = 'Im the fifth deploy for base';
    public static String thirdDeploy = 'Im the sixth deploy for base';
    public static String thirdDeploy = 'Im the seventh deploy for base';

}
